cart/urls.py
from django.urls import re_path

from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^delete/(?P<product_id>\d+)/$', views.delete_from_cart, name='delete_from_cart'),
    re_path(r'^checkout/add-address/$', views.addAddress, name='add_address'),
    re_path(r'^checkout/add-address/(?P<address_id>\d+)', views.cart_detail, name='checkout_success'),
    re_path(r'^checkout/delete-address/(?P<address_id>\d+)/$', views.deleteAddress, name='delete_address'),
    re_path(r'^$', views.cart_detail, name='cart_detail'),
]

shopping/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^signin/', include('signin.urls', namespace='signin')),
    re_path(r'^search/', include('search.urls', namespace='search')),
    re_path(r'^cart/', include('cart.urls', namespace='cart')),
    re_path(r'^order/', include('order.urls', namespace='order')),
    re_path(r'^', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User

from shop.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def subTotal(self):
        return self.quantity * self.product.price

    def __str__(self):
        return self.product


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, default=None)
    addressLine1 = models.CharField(max_length=255)
    addressLine2 = models.CharField(max_length=255)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    pincode = models.CharField(max_length=50, default=None)

    class Meta:
        db_table = 'Address'

    def __str__(self):
        return "Address:", self.user

cart/forms.py
from django import forms

from .models import Address


class AddressForm(forms.Form):
    name = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    address1 = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Address Line 1'}))
    address2 = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Address Line 2'}))
    state = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'State'}))
    city = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'City'}))
    pincode = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Pincode'}))

    def clean_address1(self):
        return self.cleaned_data['address1']

    def clean_address2(self):
        return self.cleaned_data['address2']

    def clean_state(self):
        return self.cleaned_data['state']

    def clean_city(self):
        return self.cleaned_data['city']

    def clean_pincode(self):
        return self.cleaned_data['pincode']

    def clean_name(self):
        return self.cleaned_data['name']

    def save(self, request):
        save_address = Address.objects.create(
            user=request.user,
            name=self.cleaned_data['name'],
            addressLine1=self.cleaned_data['address1'],
            addressLine2=self.cleaned_data['address2'],
            state=self.cleaned_data['state'],
            city=self.cleaned_data['city'],
            pincode=self.cleaned_data['pincode']
        )

    class Meta:
        fields = ['address1', 'address2', 'state', 'pincode', ]

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User

from .models import Cart, CartItem, Address
from .forms import AddressForm
from shop.models import Product
from order.models import Order, OrderItem


def _cart_id(request):
    cart = request.session.session_key

    if not cart:
        cart = request.session.create()

    return cart


def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)

        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1

        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )

        cart_item.save()

    return redirect('cart:cart_detail')


def remove_from_cart(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)

    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()

    else:
        cart_item.delete()

    return redirect('cart:cart_detail')


def delete_from_cart(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)

    cart_item.delete()

    return redirect('cart:cart_detail')


def cart_detail(request, total=0, cart_items=None, address_id=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.quantity * cart_item.product.price)

    except ObjectDoesNotExist:
        pass

    if request.method == 'POST':
        print(request.POST)

        user = User.objects.get(username=request.user)
        emailAddress = user.email

        address = Address.objects.get(id=address_id)
        name = address.name
        addressLine1 = address.addressLine1
        addressLine2 = address.addressLine2
        state = address.state
        city = address.city
        pincode = address.pincode

        razorpay_payment_id = request.POST['razorpay_payment_id']

        new_order = Order.objects.create(
            payment_id=razorpay_payment_id,
            total=total,
            shippingName=name,
            shippingAddressLine1=addressLine1,
            shippingAddressLine2=addressLine2,
            shippingState=state,
            shippingCity=city,
            shippingPincode=pincode,
            emailAddress=emailAddress
        )
        new_order.save()

        for item in cart_items:
            order_item = OrderItem.objects.create(
                order=new_order,
                product=item.product.name,
                quantity=item.quantity,
                price=item.product.price
            )
            order_item.save()

            products = Product.objects.get(id=item.product.id)
            products.stock = int(item.product.stock - item.quantity)
            products.save()

            item.delete()

        return redirect('order:thanks', new_order.id)

    return render(request, 'cart.html', dict(
        cart_items=cart_items,
        total=total,
    ))


def addAddress(request):
    saved_addresses = None

    try:
        user = User.objects.get(username=request.user)
        saved_addresses = Address.objects.filter(user=user)
    except Exception:
        pass

    if request.method == "POST":
        new_address = AddressForm(request.POST)

        if new_address.is_valid():
            new_address.save(request)

    else:
        new_address = AddressForm()

    return render(request, 'address/address.html', dict(saved_addresses=saved_addresses, new_address=new_address))


def deleteAddress(request, address_id):
    user = User.objects.get(username=request.user)
    address = Address.objects.get(user=user, id=address_id)

    address.delete()

    return redirect('cart:add_address')

cart/templates/address/address.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}
	<title>Choose a Shipping and Billing Address - New Age Electronics</title>
{% endblock %}

{% block content %}
	<div class="container mb-3 border-bottom">
        <table class="table">
            <thead>
                <tr>
                    <th colspan="6" class="text-center">
                        Saved Addresses
                    </th>
                </tr>
            </thead>
            <tbody>
                {% if saved_addresses %} 
                    {% for saved_address in saved_addresses %}
                        <tr>
                            <td colspan="4">
                                {{ saved_address.name }}<br>
                                {{ saved_address.addressLine1 }}<br>
                                {{ saved_address.addressLine2 }}<br>
                                {{ saved_address.state }}<br>
                                {{ saved_address.city }}<br>
                                {{ saved_address.pincode }}
                            </td>
                            <td>
                                <form action="{% url 'cart:checkout_success' saved_address.id %}" method="POST">
                                    {% csrf_token %}
                                    <script
                                        src="https://checkout.razorpay.com/v1/checkout.js"
                                        data-key="rzp_test_21hu8pcAtLm4a4"
                                        data-amount="{{ razorpay_total }}"
                                        data-buttontext="Deliver Here"
                                        data-name="New Age Electronicsp"
                                        data-description=""
                                        data-image="{% static "img/logo.png" %}"
                                        data-prefill.name="Prasun Philip"
                                        data-prefill.email="support@newage.com"
                                        data-theme.color="#F37254"
                                    ></script>
                                    <input type="hidden" value="Hidden Element" name="hidden">
                                </form>
                                <a href="{% url 'cart:delete_address' saved_address.id %}" class="btn btn-outline-danger">Delete this address</a>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>
                            <h5>You have no saved addresses.</h5>
                        </td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
	</div>
    <div class="container border border-primary p-4 rounded">
        <h3>Add a new shipping address.</h3>
        <form action="{% url 'cart:add_address' %}" class="form-group" method="POST" novalidate>
            {% csrf_token %}

            {% if new_address.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    {% for error in new_address.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
            {% for field in new_address.visible_fields %}
                {% if new_address.is_bound %}
                    {% if field.errors %}
                        {% render_field field class="form-control is-invalid mb-2" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback">
                                {{ error }}
                            </div>
                        {% endfor %}
                    {% else %}
                        {% render_field field class="form-control is-valid mb-2" %}
                    {% endif %}
                {% else %}
                    {% render_field field class="form-control mb-2" %}
                {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary mx-auto">Add new address</button>
        </form>
    </div>
{% endblock %}