cart/urls.py
from django.urls import re_path

from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^delete/(?P<product_id>\d+)/$', views.delete_from_cart, name='delete_from_cart'),
    re_path(r'^checkout/add-address/$', views.addAddress, name='add_address'),
    re_path(r'^checkout/add-address/(?P<address_id>\d+)', views.cart_detail, name='checkout_success'),
    re_path(r'^checkout/delete-address/(?P<address_id>\d+)/$', views.deleteAddress, name='delete_address'),
    re_path(r'^$', views.cart_detail, name='cart_detail'),
]

order/urls.py
from django.urls import re_path

from . import views

app_name = 'order'

urlpatterns = [
    re_path(r'^thank-you/(?P<order_id>\d+)/$', views.thankYou, name='thanks'),
    re_path(r'^order-history/$', views.orderHistory, name='order_history'),
    re_path(r'^order-history/view-order/(?P<order_id>\d+)/$', views.orderHistoryDetail, name='order_history_detail'),
]

search/urls.py
from django.urls import re_path

from . import views

app_name = 'search'

urlpatterns = [
    re_path(r'^$', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import re_path

from . import views

app_name = 'shop'

urlpatterns = [
    re_path(r'^(?P<category_slug>[\w-]+)/$', views.allProds, name='products_by_category'),
    re_path(r'^(?P<category_slug>[\w-]+)/(?P<product_slug>[\w-]+)/$', views.prodDetail, name='product_detail'),
    re_path(r'^$', views.allProds, name='home'),
]

shopping/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^signin/', include('signin.urls', namespace='signin')),
    re_path(r'^search/', include('search.urls', namespace='search')),
    re_path(r'^cart/', include('cart.urls', namespace='cart')),
    re_path(r'^order/', include('order.urls', namespace='order')),
    re_path(r'^', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signin/urls.py
from django.urls import re_path

from . import views

app_name = 'signin'

urlpatterns = [
    re_path(r'^$', views.signinView, name = 'login'),
    re_path(r'^signup/$', views.signupView, name = 'signup'),
    re_path(r'^signout/$', views.signoutView, name = 'signout'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField(blank=True)

    image = models.ImageField(upload_to='categories', blank=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    manufacturer = models.CharField(max_length=255)
    name = models.CharField(max_length=255, unique=True)
    model_number = models.CharField(max_length=255, default=None)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.TextField(default=None)

    warranty_type = models.CharField(max_length=50, default=None)
    warranty_duration = models.CharField(max_length=100, default=None)

    price = models.DecimalField(max_digits=12, decimal_places=2)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    stock = models.PositiveIntegerField()

    available = models.BooleanField(default=True)

    image = models.ImageField(upload_to='product', null=True)
    thumbnail = models.ImageField(upload_to='product_thumbnails', null=True)

    class Meta:
        ordering = ('name', 'created', 'updated', )
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def get_url(self):
        return reverse('shop:product_detail', args=[self.category.slug, self.slug, ])

    def __str__(self):
        return 'Product ({}): {} {}'.format(self.category.name, self.manufacturer, self.name)

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product


def allProds(request, category_slug=None):
    product_list = None
    category_page = None

    if category_slug is not None:
        category_page = get_object_or_404(Category, slug=category_slug)
        product_list = Product.objects.filter(category=category_page, available=True)

    else:
        product_list = Product.objects.all().filter(available=True).order_by('-created')[:9]

    return render(request, 'shop/category.html', {'category': category_page, 'product_list': product_list})


def prodDetail(request, category_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=category_slug, slug=product_slug)
    except Exception as e:
        raise e

    return render(request, 'shop/product-detail.html', {'product': product})

shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/all.css' %}">
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">

        {% block title %}<title>New Age Electronics</title>{% endblock %}
    </head>

    <body>
        <div class="container">
            {% include 'logo-header.html' %}
            {% include 'welcome-banner.html' %}
            {% include 'navbar.html' %}

            {% block content %}
            {% endblock %}
        </div>

        <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/all.js' %}"></script>
        <script src="{% static 'js/custom.js' %}"></script>
    </body>
</html>

shop/templates/logo-header.html
{% load staticfiles %}

<header class="py-3">
    <center>
        <a href="{% url 'shop:home' %}"><img src="{% static 'img/logo.svg' %}" style="width: 8cm"></a>
    </center>
</header>

shop/templates/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expand="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:home' %}">Home</a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Shop
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'shop:home' %}">All Products</a>
                    {% for category in categories %}
                        <a class="dropdown-item" href="{{ category.get_url }}">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </li>

            <li class="nav-item">
                {% if not request.user.is_authenticated %}
                    <a class="nav-link disabled" style="cursor: not-allowed;" data-toggle="tooltip" data-placement="right" title="Sign in to use the cart"><i class="fas fa-shopping-cart"></i></a>
                {% else %}
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{ counter }})</a>
                {% endif %}
            </li>
        </ul>

        <form class="form-inline my-2 my-lg-0" action="{% url 'search:searchResult' %}" method="get">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-primary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>
</nav>

shop/templates/welcome-banner.html
{% load staticfiles %}

<div class="container">
    {% if request.user.is_authenticated %}
        {% if request.user.first_name %}
            <div class = "row alert alert alert-primary" role = "alert">
                <div class="col-12 col-md-6 col-sm-6 col-lg-6">
                    Welcome, <a href="#" class="dropdown-toggle" style="color: inherit;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ request.user.first_name }}</a>
                    <div class="dropdown-menu dropdown-menu-center">
                        <a href="{% url 'order:order_history' %}" class="dropdown-item">Your Orders</a>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-sm-6 col-lg-6">
                    <div class="col-12 offset-sm-7 col-sm-8 offset-sm-4 text-center">
                        <a href="{% url 'signin:signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
                    </div>
                </div>
            </div>

        {% else %}
            <div class="row alert alert-primary" role="alert">
                <div class="col-12 col-md-12 col-lg-6">
                    Welcome, <a href="#" class="dropdown-toggle" style="color: inherit;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">User</a>
                    <div class="dropdown-menu dropdown-menu-center">
                        <a href="{% url 'order:order_history' %}" class="dropdown-item">Your Orders</a>
                    </div>
                </div>

                <div class="col-12 col-md-6 col-sm-6 col-lg-6">
                    <div class="col-12 offset-sm-7 col-sm-8 offset-sm-4 text-center">
                        <a class="text-right" href="{% url 'signin:signout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
                    </div>
                </div>
            </div>
        {% endif %}

    {% else %}
        <div class="row alert alert-warning" role="alert">
            <div class="mx-auto">
                Please <a href="{% url 'signin:login' %}">Sign In <i class="fas fa-sign-in-alt"></i></a> or <a href="{% url 'signin:signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
            </div>
        </div>
    {% endif %}
</div>