cart/urls.py
from django.urls import re_path

from . import views

app_name = 'cart'

urlpatterns = [
    re_path(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^delete/(?P<product_id>\d+)/$', views.delete_from_cart, name='delete_from_cart'),
    re_path(r'^checkout/add-address/$', views.addAddress, name='add_address'),
    re_path(r'^checkout/add-address/(?P<address_id>\d+)', views.cart_detail, name='checkout_success'),
    re_path(r'^checkout/delete-address/(?P<address_id>\d+)/$', views.deleteAddress, name='delete_address'),
    re_path(r'^$', views.cart_detail, name='cart_detail'),
]

order/urls.py
from django.urls import re_path

from . import views

app_name = 'order'

urlpatterns = [
    re_path(r'^thank-you/(?P<order_id>\d+)/$', views.thankYou, name='thanks'),
    re_path(r'^order-history/$', views.orderHistory, name='order_history'),
    re_path(r'^order-history/view-order/(?P<order_id>\d+)/$', views.orderHistoryDetail, name='order_history_detail'),
]

shop/urls.py
from django.urls import re_path

from . import views

app_name = 'shop'

urlpatterns = [
    re_path(r'^(?P<category_slug>[\w-]+)/$', views.allProds, name='products_by_category'),
    re_path(r'^(?P<category_slug>[\w-]+)/(?P<product_slug>[\w-]+)/$', views.prodDetail, name='product_detail'),
    re_path(r'^$', views.allProds, name='home'),
]

shopping/urls.py
from django.contrib import admin
from django.urls import re_path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^signin/', include('signin.urls', namespace='signin')),
    re_path(r'^search/', include('search.urls', namespace='search')),
    re_path(r'^cart/', include('cart.urls', namespace='cart')),
    re_path(r'^order/', include('order.urls', namespace='order')),
    re_path(r'^', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models


class Order(models.Model):
    payment_id = models.CharField(max_length=255)
    total = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='Order total (INR)')

    created = models.DateTimeField(auto_now_add=True)

    emailAddress = models.EmailField(max_length=255, verbose_name='E-mail Address')
    shippingName = models.CharField(max_length=255)
    shippingAddressLine1 = models.CharField(max_length=255)
    shippingAddressLine2 = models.CharField(max_length=255)
    shippingState = models.CharField(max_length=255)
    shippingCity = models.CharField(max_length=255)
    shippingPincode = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'
        db_table = 'Order'
        ordering = ['created', ]

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    product = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='Product Price (INR)')

    class Meta:
        db_table = 'OrderItem'
        verbose_name = 'Order Item'
        verbose_name_plural = 'Order Items'

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return self.product

order/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from order.models import Order, OrderItem


def thankYou(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, id=order_id)

    return render(request, 'thanks.html', {'customer_order': customer_order, })


@login_required(login_url='/signin/')
def orderHistory(request):
    email = str(request.user.email)
    order_list = Order.objects.filter(emailAddress=email)

    return render(request, 'order/order_list.html', {'order_list': order_list, })


@login_required(login_url='/signin/')
def orderHistoryDetail(request, order_id):
    email = str(request.user.email)
    order = Order.objects.get(id=order_id, emailAddress=email)
    order_detail = OrderItem.objects.filter(order=order)

    return render(request, 'order/order_detail.html', dict(order=order, order_detail=order_detail))

order/templates/order/order_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load humanize %}

{% block title %}
    <title>Order Details - New Age Electronics</title>
{% endblock title %}

{% block content %}
    <div>
        <div class="text-center">
            <br>
            <h1>Order Details</h1>
            <br>
            <table class="table table-bordered">
                <tr>
                    <td class="text-left" colspan="2">
                        <strong>Order No.: {{ order.id }}</strong><br>
                        <strong>Date: {{ order.created | date:"d M Y" }}</strong><br>
                        <strong>Order Total: {{ order.total }}</strong>
                    </td>
                    <td class="text-left" colspan="2">
                        <strong>Shipping Address:</strong><br>
                        {{ order.shippingName }}<br>
                        {{ order.shippingAddressLine1 }}<br>
                        {{ order.shippingAddressLine2 }}<br>
                        {{ order.shippingState }}<br>
                        {{ order.shippingCity }}<br>
                        {{ order.shippingPincode }}<br>
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>Product Description</strong>
                    </td>
                    <td>
                        <strong>Quantity</strong>
                    </td>
                    <td>
                        <strong>Unit Price</strong>
                    </td>
                    <td>
                        <strong>Sub Total</strong>
                    </td>
                </tr>
                {% for item in order_detail %}
                    <tr>
                        <td>
                            {{ item.product }}
                        </td>
                        <td>
                            {{ item.quantity | intcomma }}
                        </td>
                        <td>
                            {{ item.product.price | intcomma }}
                        </td>
                        <td>
                            {{ item.sub_total }}
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td class="text-right" colspan="3">
                        <strong>Total</strong>
                    </td>
                    <td>
                        &#x20b9;{{ order.total | intcomma }}
                    </td>
                </tr>
                <tr>
                    <td class="text-left" colspan="4">
                        <strong>Payment Details: </strong><br>
                        The order #{{ order.id }} has been paid successfully via Razorpay.
                    </td>
                </tr>
            </table>
            <button class="btn btn-primary" onclick="window.print();">Print Order</button>
            <br><br>
        </div>
    </div>
{% endblock content %}

order/templates/order/order_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    <title>Your order history - New Age Electronics</title>
{% endblock title %}

{% block content %}
    <div>
        <div class="text-center">
            <br>
            <h1>Your order history</h1>
            {% if order_list %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Order Number</th>
                            <th>Order Date</th>
                            <th>Total Price</th>
                            <th>Payment Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in order_list %}
                            <tr>
                                <td>{{ order.id }}</td>
                                <td>{{ order.created | date:"d M Y" }}</td>
                                <td>{{ order.total }}</td>
                                <td><i class="fas fa-check"></i>Completed</td>
                                <td><a href="{% url 'order:order_history_detail' order.id %}">View Order</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>
                    You have not placed any order yet!<br><br>
                    <a href="{% url 'shop:home' %}" class="btn btn-outline-primary text-center">Go to the shop</a>
                </p>
            {% endif %}
        </div>
    </div>
{% endblock content %}